services:
  celery-beat:
    build:
      context: ${CURRENT_DIR}docker
      dockerfile: Dockerfile.dev
    container_name: celery-beat
    image: sparrow-local:latest
    command: run-celery-beat
    volumes:
      - ${CURRENT_DIR}docker/files/app:/app
    env_file:
      - ${CURRENT_DIR}.envs/.local/
    depends_on:
      - django-server
      - redis-server
    network_mode: host
