services:
  postgis-server:
    image: postgis:latest
    container_name: postgis-server
    env_file:
      - ${CURRENT_DIR}.envs/.local/.postgres
    volumes:
      - ${CURRENT_DIR}data/postgres:/postgres
      - ${CURRENT_DIR}.includes/docker-compose/postgis-server:/docker-entrypoint-initdb.d
    ports:
      - "5332:5432"
    network_mode: host
